
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button btnSumar;
	private global::Gtk.Button btnRestar;
	private global::Gtk.Button btnMul;
	private global::Gtk.Button btnDiv;
	private global::Gtk.Label lblNumero1;
	private global::Gtk.Label lblNumero2;
	private global::Gtk.Label lblResultado;
	private global::Gtk.Entry Numero1;
	private global::Gtk.Entry Numero2;
	private global::Gtk.Entry Resultado;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSumar = new global::Gtk.Button ();
		this.btnSumar.CanFocus = true;
		this.btnSumar.Name = "btnSumar";
		this.btnSumar.UseUnderline = true;
		this.btnSumar.Label = global::Mono.Unix.Catalog.GetString ("Sumar");
		this.fixed1.Add (this.btnSumar);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnSumar]));
		w1.X = 24;
		w1.Y = 211;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnRestar = new global::Gtk.Button ();
		this.btnRestar.CanFocus = true;
		this.btnRestar.Name = "btnRestar";
		this.btnRestar.UseUnderline = true;
		this.btnRestar.Label = global::Mono.Unix.Catalog.GetString ("Restar");
		this.fixed1.Add (this.btnRestar);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnRestar]));
		w2.X = 121;
		w2.Y = 211;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnMul = new global::Gtk.Button ();
		this.btnMul.CanFocus = true;
		this.btnMul.Name = "btnMul";
		this.btnMul.UseUnderline = true;
		this.btnMul.Label = global::Mono.Unix.Catalog.GetString ("Multiplicar");
		this.fixed1.Add (this.btnMul);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnMul]));
		w3.X = 209;
		w3.Y = 211;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnDiv = new global::Gtk.Button ();
		this.btnDiv.CanFocus = true;
		this.btnDiv.Name = "btnDiv";
		this.btnDiv.UseUnderline = true;
		this.btnDiv.Label = global::Mono.Unix.Catalog.GetString ("Dividir");
		this.fixed1.Add (this.btnDiv);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnDiv]));
		w4.X = 304;
		w4.Y = 211;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblNumero1 = new global::Gtk.Label ();
		this.lblNumero1.Name = "lblNumero1";
		this.lblNumero1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero1");
		this.fixed1.Add (this.lblNumero1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblNumero1]));
		w5.X = 58;
		w5.Y = 20;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblNumero2 = new global::Gtk.Label ();
		this.lblNumero2.Name = "lblNumero2";
		this.lblNumero2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero2");
		this.fixed1.Add (this.lblNumero2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblNumero2]));
		w6.X = 59;
		w6.Y = 57;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblResultado = new global::Gtk.Label ();
		this.lblResultado.Name = "lblResultado";
		this.lblResultado.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.lblResultado);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblResultado]));
		w7.X = 60;
		w7.Y = 96;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero1 = new global::Gtk.Entry ();
		this.Numero1.CanFocus = true;
		this.Numero1.Name = "Numero1";
		this.Numero1.IsEditable = true;
		this.Numero1.InvisibleChar = '●';
		this.fixed1.Add (this.Numero1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero1]));
		w8.X = 145;
		w8.Y = 18;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero2 = new global::Gtk.Entry ();
		this.Numero2.CanFocus = true;
		this.Numero2.Name = "Numero2";
		this.Numero2.IsEditable = true;
		this.Numero2.InvisibleChar = '●';
		this.fixed1.Add (this.Numero2);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero2]));
		w9.X = 145;
		w9.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Resultado = new global::Gtk.Entry ();
		this.Resultado.CanFocus = true;
		this.Resultado.Name = "Resultado";
		this.Resultado.IsEditable = true;
		this.Resultado.InvisibleChar = '●';
		this.fixed1.Add (this.Resultado);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Resultado]));
		w10.X = 145;
		w10.Y = 90;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnSumar.Clicked += new global::System.EventHandler (this.OnBtnSumarClicked);
		this.btnRestar.Clicked += new global::System.EventHandler (this.OnBtnRestarClicked);
		this.btnMul.Clicked += new global::System.EventHandler (this.OnBtnMulClicked);
		this.btnDiv.Clicked += new global::System.EventHandler (this.OnBtnDivClicked);
	}
}
